---
title: OpenActive
timezone: UTC
collections:
  booking_engines:
    title: Booking Systems
    output: true
  case_studies:
    title: Case Studies
    output: true
  events:
    title: Events
    output: true
  faqs:
    title: FAQs
    output: true
  members:
    title: Members
    output: true
  mentors:
    title: Mentors
    output: true
  partners:
    title: Partners
    output: true
  dataproviders:
    title: Data Providers
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: "/uploads/:path/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_main_navigation: false
    is_secondary_navigation: false
- scope:
    path: ''
    type: posts
  values:
    layout: post
    is_featured: false
    thumbnail_image: ''
    categories: About OpenActive
- scope:
    path: ''
    type: case_studies
  values:
    layout: case-study
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    member: 
    strapline: 
- scope:
    path: ''
    type: mentors
  values:
    layout: mentor
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    twitter: 
    linkedin: 
    role: 
- scope:
    path: ''
    type: partners
  values:
    layout: partner
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
- scope:
    path: ''
    type: members
  values:
    layout: member
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    website: Web address
- scope:
    path: ''
    type: booking_engines
  values:
    layout: booking-engine
    is_featured: false
    is_enabled: false
    thumbnail_image: "/uploads/placeholder.png"
    member: 
    website: Web address
compress_html:
  blanklines: false
  profile: false
locale: en-US
description: Helping physical activity reach everyone. OpenActive is community-led
  initiative with an ambition to help people in England get active using open data.
baseurl: "/openactive-staging"
url: https://imaginatecreative.github.io
repository: imaginatecreative/openactive-staging
email: your-email@example.com
github_username: imaginatecreative
twitter_username: twitter
youtube_username: 
facebook_username: 
instagram_username: 
pinterest_username: 
medium_username: medium
markdown: kramdown
plugins:
- jekyll-feed
staticman:
  branch: master
reCaptcha:
  siteKey: sitekey
  secret: 
atom_feed:
  path: 
search: 
search_full_content: 
tipue_search:
  include:
    pages: true
